//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dataweb.Dilab.Web.OrdemServicoServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OrdemServicoServiceReference.IOrdemServicoService")]
    public interface IOrdemServicoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdemServicoService/FindAllByCodCliente", ReplyAction="http://tempuri.org/IOrdemServicoService/FindAllByCodClienteResponse")]
        Dataweb.Dilab.Model.DataTransfer.OrdemServicoQuery[] FindAllByCodCliente(int codCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdemServicoService/FindAllByCodClienteAndReferencia", ReplyAction="http://tempuri.org/IOrdemServicoService/FindAllByCodClienteAndReferenciaResponse")]
        Dataweb.Dilab.Model.DataTransfer.OrdemServicoQuery[] FindAllByCodClienteAndReferencia(int codCliente, string referencia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdemServicoService/FindAllByLogin", ReplyAction="http://tempuri.org/IOrdemServicoService/FindAllByLoginResponse")]
        Dataweb.Dilab.Model.DataTransfer.OrdemServicoQuery[] FindAllByLogin(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdemServicoService/FindAllByLoginAndReferencia", ReplyAction="http://tempuri.org/IOrdemServicoService/FindAllByLoginAndReferenciaResponse")]
        Dataweb.Dilab.Model.DataTransfer.OrdemServicoQuery[] FindAllByLoginAndReferencia(string login, string referencia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdemServicoService/FindAllFamilia", ReplyAction="http://tempuri.org/IOrdemServicoService/FindAllFamiliaResponse")]
        Dataweb.Dilab.Model.DataTransfer.Familia[] FindAllFamilia();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdemServicoService/FindAllMaterial", ReplyAction="http://tempuri.org/IOrdemServicoService/FindAllMaterialResponse")]
        Dataweb.Dilab.Model.DataTransfer.Material[] FindAllMaterial();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdemServicoService/GetCountFechadas", ReplyAction="http://tempuri.org/IOrdemServicoService/GetCountFechadasResponse")]
        int GetCountFechadas(int codCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdemServicoService/GetCountEmProducao", ReplyAction="http://tempuri.org/IOrdemServicoService/GetCountEmProducaoResponse")]
        int GetCountEmProducao(int codCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdemServicoService/FindAllProdutoServico", ReplyAction="http://tempuri.org/IOrdemServicoService/FindAllProdutoServicoResponse")]
        Dataweb.Dilab.Model.DataTransfer.ProdutoServico[] FindAllProdutoServico(int codFamilia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdemServicoService/InsertOrdemServico", ReplyAction="http://tempuri.org/IOrdemServicoService/InsertOrdemServicoResponse")]
        void InsertOrdemServico(Dataweb.Dilab.Model.DataTransfer.OrdemServicoOtica dto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IOrdemServicoServiceChannel : Dataweb.Dilab.Web.OrdemServicoServiceReference.IOrdemServicoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class OrdemServicoServiceClient : System.ServiceModel.ClientBase<Dataweb.Dilab.Web.OrdemServicoServiceReference.IOrdemServicoService>, Dataweb.Dilab.Web.OrdemServicoServiceReference.IOrdemServicoService {
        
        public OrdemServicoServiceClient() {
        }
        
        public OrdemServicoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrdemServicoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrdemServicoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrdemServicoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Dataweb.Dilab.Model.DataTransfer.OrdemServicoQuery[] FindAllByCodCliente(int codCliente) {
            return base.Channel.FindAllByCodCliente(codCliente);
        }
        
        public Dataweb.Dilab.Model.DataTransfer.OrdemServicoQuery[] FindAllByCodClienteAndReferencia(int codCliente, string referencia) {
            return base.Channel.FindAllByCodClienteAndReferencia(codCliente, referencia);
        }
        
        public Dataweb.Dilab.Model.DataTransfer.OrdemServicoQuery[] FindAllByLogin(string login) {
            return base.Channel.FindAllByLogin(login);
        }
        
        public Dataweb.Dilab.Model.DataTransfer.OrdemServicoQuery[] FindAllByLoginAndReferencia(string login, string referencia) {
            return base.Channel.FindAllByLoginAndReferencia(login, referencia);
        }
        
        public Dataweb.Dilab.Model.DataTransfer.Familia[] FindAllFamilia() {
            return base.Channel.FindAllFamilia();
        }
        
        public Dataweb.Dilab.Model.DataTransfer.Material[] FindAllMaterial() {
            return base.Channel.FindAllMaterial();
        }
        
        public int GetCountFechadas(int codCliente) {
            return base.Channel.GetCountFechadas(codCliente);
        }
        
        public int GetCountEmProducao(int codCliente) {
            return base.Channel.GetCountEmProducao(codCliente);
        }
        
        public Dataweb.Dilab.Model.DataTransfer.ProdutoServico[] FindAllProdutoServico(int codFamilia) {
            return base.Channel.FindAllProdutoServico(codFamilia);
        }
        
        public void InsertOrdemServico(Dataweb.Dilab.Model.DataTransfer.OrdemServicoOtica dto) {
            base.Channel.InsertOrdemServico(dto);
        }
    }
}
