//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dataweb.Dilab.Web.ClienteServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ClienteServiceReference.IClienteService")]
    public interface IClienteService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/FindByLogin", ReplyAction="http://tempuri.org/IClienteService/FindByLoginResponse")]
        Dataweb.Dilab.Model.DataTransfer.Cliente FindByLogin(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/ValidateLogin", ReplyAction="http://tempuri.org/IClienteService/ValidateLoginResponse")]
        bool ValidateLogin(string login, string senha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/ChangePassword", ReplyAction="http://tempuri.org/IClienteService/ChangePasswordResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Dataweb.Dilab.Model.Wcf.DatawebFault), Action="http://tempuri.org/IClienteService/ChangePasswordDatawebFaultFault", Name="DatawebFault", Namespace="http://schemas.datacontract.org/2004/07/Dataweb.Dilab.Model.Wcf")]
        void ChangePassword(string login, string currentPassword, string newPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/ChangeEmail", ReplyAction="http://tempuri.org/IClienteService/ChangeEmailResponse")]
        void ChangeEmail(string login, string emailNotificacao, bool receberNotificacao);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IClienteServiceChannel : Dataweb.Dilab.Web.ClienteServiceReference.IClienteService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ClienteServiceClient : System.ServiceModel.ClientBase<Dataweb.Dilab.Web.ClienteServiceReference.IClienteService>, Dataweb.Dilab.Web.ClienteServiceReference.IClienteService {
        
        public ClienteServiceClient() {
        }
        
        public ClienteServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClienteServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClienteServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClienteServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Dataweb.Dilab.Model.DataTransfer.Cliente FindByLogin(string login) {
            return base.Channel.FindByLogin(login);
        }
        
        public bool ValidateLogin(string login, string senha) {
            return base.Channel.ValidateLogin(login, senha);
        }
        
        public void ChangePassword(string login, string currentPassword, string newPassword) {
            base.Channel.ChangePassword(login, currentPassword, newPassword);
        }
        
        public void ChangeEmail(string login, string emailNotificacao, bool receberNotificacao) {
            base.Channel.ChangeEmail(login, emailNotificacao, receberNotificacao);
        }
    }
}
