//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dataweb.Dilab.Web.ProdutoServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProdutoServiceReference.IProdutoService")]
    public interface IProdutoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoService/FindAllByCodCliente", ReplyAction="http://tempuri.org/IProdutoService/FindAllByCodClienteResponse")]
        Dataweb.Dilab.Model.DataTransfer.OrdemServicoQuery[] FindAllByCodCliente(int codCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoService/FindAllByCodClienteAndReferencia", ReplyAction="http://tempuri.org/IProdutoService/FindAllByCodClienteAndReferenciaResponse")]
        Dataweb.Dilab.Model.DataTransfer.OrdemServicoQuery[] FindAllByCodClienteAndReferencia(int codCliente, string referencia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoService/FindAllByLogin", ReplyAction="http://tempuri.org/IProdutoService/FindAllByLoginResponse")]
        Dataweb.Dilab.Model.DataTransfer.OrdemServicoQuery[] FindAllByLogin(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoService/FindAllByLoginAndReferencia", ReplyAction="http://tempuri.org/IProdutoService/FindAllByLoginAndReferenciaResponse")]
        Dataweb.Dilab.Model.DataTransfer.OrdemServicoQuery[] FindAllByLoginAndReferencia(string login, string referencia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoService/FindAllFamilia", ReplyAction="http://tempuri.org/IProdutoService/FindAllFamiliaResponse")]
        Dataweb.Dilab.Model.DataTransfer.Familia[] FindAllFamilia();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoService/FindAllMaterial", ReplyAction="http://tempuri.org/IProdutoService/FindAllMaterialResponse")]
        Dataweb.Dilab.Model.DataTransfer.Material[] FindAllMaterial();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoService/GetCountFechadas", ReplyAction="http://tempuri.org/IProdutoService/GetCountFechadasResponse")]
        int GetCountFechadas(int codCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoService/GetCountEmProducao", ReplyAction="http://tempuri.org/IProdutoService/GetCountEmProducaoResponse")]
        int GetCountEmProducao(int codCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoService/FindAllServico", ReplyAction="http://tempuri.org/IProdutoService/FindAllServicoResponse")]
        Dataweb.Dilab.Model.DataTransfer.Servico[] FindAllServico(int codFamilia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoService/FindAllProduto", ReplyAction="http://tempuri.org/IProdutoService/FindAllProdutoResponse")]
        Dataweb.Dilab.Model.DataTransfer.Produto[] FindAllProduto(int codFamilia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoService/InsertOrdemServico", ReplyAction="http://tempuri.org/IProdutoService/InsertOrdemServicoResponse")]
        Dataweb.Dilab.Model.DataTransfer.OrdemServicoOtica InsertOrdemServico(Dataweb.Dilab.Model.DataTransfer.OrdemServicoOtica dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoService/InsertPedido", ReplyAction="http://tempuri.org/IProdutoService/InsertPedidoResponse")]
        Dataweb.Dilab.Model.DataTransfer.Pedido InsertPedido(Dataweb.Dilab.Model.DataTransfer.Pedido dto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IProdutoServiceChannel : Dataweb.Dilab.Web.ProdutoServiceReference.IProdutoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ProdutoServiceClient : System.ServiceModel.ClientBase<Dataweb.Dilab.Web.ProdutoServiceReference.IProdutoService>, Dataweb.Dilab.Web.ProdutoServiceReference.IProdutoService {
        
        public ProdutoServiceClient() {
        }
        
        public ProdutoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProdutoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProdutoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProdutoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Dataweb.Dilab.Model.DataTransfer.OrdemServicoQuery[] FindAllByCodCliente(int codCliente) {
            return base.Channel.FindAllByCodCliente(codCliente);
        }
        
        public Dataweb.Dilab.Model.DataTransfer.OrdemServicoQuery[] FindAllByCodClienteAndReferencia(int codCliente, string referencia) {
            return base.Channel.FindAllByCodClienteAndReferencia(codCliente, referencia);
        }
        
        public Dataweb.Dilab.Model.DataTransfer.OrdemServicoQuery[] FindAllByLogin(string login) {
            return base.Channel.FindAllByLogin(login);
        }
        
        public Dataweb.Dilab.Model.DataTransfer.OrdemServicoQuery[] FindAllByLoginAndReferencia(string login, string referencia) {
            return base.Channel.FindAllByLoginAndReferencia(login, referencia);
        }
        
        public Dataweb.Dilab.Model.DataTransfer.Familia[] FindAllFamilia() {
            return base.Channel.FindAllFamilia();
        }
        
        public Dataweb.Dilab.Model.DataTransfer.Material[] FindAllMaterial() {
            return base.Channel.FindAllMaterial();
        }
        
        public int GetCountFechadas(int codCliente) {
            return base.Channel.GetCountFechadas(codCliente);
        }
        
        public int GetCountEmProducao(int codCliente) {
            return base.Channel.GetCountEmProducao(codCliente);
        }
        
        public Dataweb.Dilab.Model.DataTransfer.Servico[] FindAllServico(int codFamilia) {
            return base.Channel.FindAllServico(codFamilia);
        }
        
        public Dataweb.Dilab.Model.DataTransfer.Produto[] FindAllProduto(int codFamilia) {
            return base.Channel.FindAllProduto(codFamilia);
        }
        
        public Dataweb.Dilab.Model.DataTransfer.OrdemServicoOtica InsertOrdemServico(Dataweb.Dilab.Model.DataTransfer.OrdemServicoOtica dto) {
            return base.Channel.InsertOrdemServico(dto);
        }
        
        public Dataweb.Dilab.Model.DataTransfer.Pedido InsertPedido(Dataweb.Dilab.Model.DataTransfer.Pedido dto) {
            return base.Channel.InsertPedido(dto);
        }
    }
}
