//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dataweb.Dilab.Web.ProdutoServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProdutoServiceReference.IProdutoService")]
    public interface IProdutoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoService/FindAllTransacaoByLogin", ReplyAction="http://tempuri.org/IProdutoService/FindAllTransacaoByLoginResponse")]
        Dataweb.Dilab.Model.DataTransfer.Transacao[] FindAllTransacaoByLogin(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoService/FindAllTransacaoByLoginAndReferencia", ReplyAction="http://tempuri.org/IProdutoService/FindAllTransacaoByLoginAndReferenciaResponse")]
        Dataweb.Dilab.Model.DataTransfer.Transacao[] FindAllTransacaoByLoginAndReferencia(string login, string referencia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoService/FindAllFamilia", ReplyAction="http://tempuri.org/IProdutoService/FindAllFamiliaResponse")]
        Dataweb.Dilab.Model.DataTransfer.Familia[] FindAllFamilia();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoService/FindAllMaterial", ReplyAction="http://tempuri.org/IProdutoService/FindAllMaterialResponse")]
        Dataweb.Dilab.Model.DataTransfer.Material[] FindAllMaterial();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoService/GetCountFechadas", ReplyAction="http://tempuri.org/IProdutoService/GetCountFechadasResponse")]
        int GetCountFechadas(int codCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoService/GetCountEmProducao", ReplyAction="http://tempuri.org/IProdutoService/GetCountEmProducaoResponse")]
        int GetCountEmProducao(int codCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoService/FindAllServico", ReplyAction="http://tempuri.org/IProdutoService/FindAllServicoResponse")]
        Dataweb.Dilab.Model.DataTransfer.Item[] FindAllServico(int codFamilia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoService/FindAllProduto", ReplyAction="http://tempuri.org/IProdutoService/FindAllProdutoResponse")]
        Dataweb.Dilab.Model.DataTransfer.Item[] FindAllProduto(int codFamilia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoService/GetTransacao", ReplyAction="http://tempuri.org/IProdutoService/GetTransacaoResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Dataweb.Dilab.Model.DataTransfer.Pedido))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Dataweb.Dilab.Model.DataTransfer.OrdemServico))]
        Dataweb.Dilab.Model.DataTransfer.Transacao GetTransacao(int codEmpresa, int codTransacao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoService/GetOrdemServico", ReplyAction="http://tempuri.org/IProdutoService/GetOrdemServicoResponse")]
        Dataweb.Dilab.Model.DataTransfer.OrdemServico GetOrdemServico(int codEmpresa, int codTransacao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoService/GetPedido", ReplyAction="http://tempuri.org/IProdutoService/GetPedidoResponse")]
        Dataweb.Dilab.Model.DataTransfer.Pedido GetPedido(int codEmpresa, int codTransacao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoService/InsertOrdemServico", ReplyAction="http://tempuri.org/IProdutoService/InsertOrdemServicoResponse")]
        Dataweb.Dilab.Model.DataTransfer.OrdemServico InsertOrdemServico(Dataweb.Dilab.Model.DataTransfer.OrdemServico dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoService/InsertPedido", ReplyAction="http://tempuri.org/IProdutoService/InsertPedidoResponse")]
        Dataweb.Dilab.Model.DataTransfer.Pedido InsertPedido(Dataweb.Dilab.Model.DataTransfer.Pedido dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoService/FindAllFatura", ReplyAction="http://tempuri.org/IProdutoService/FindAllFaturaResponse")]
        Dataweb.Dilab.Model.DataTransfer.Fatura[] FindAllFatura(int codEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoService/FindAllLancamento", ReplyAction="http://tempuri.org/IProdutoService/FindAllLancamentoResponse")]
        Dataweb.Dilab.Model.DataTransfer.Lancamento[] FindAllLancamento(int codEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoService/FindAllNotaFiscal", ReplyAction="http://tempuri.org/IProdutoService/FindAllNotaFiscalResponse")]
        Dataweb.Dilab.Model.DataTransfer.NotaFiscal[] FindAllNotaFiscal(int codEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoService/GetFatura", ReplyAction="http://tempuri.org/IProdutoService/GetFaturaResponse")]
        Dataweb.Dilab.Model.DataTransfer.Fatura GetFatura(int codEmpresa, int codFatura);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoService/GetNotaFiscal", ReplyAction="http://tempuri.org/IProdutoService/GetNotaFiscalResponse")]
        Dataweb.Dilab.Model.DataTransfer.NotaFiscal GetNotaFiscal(int codEmpresa, int codNotaFiscal);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IProdutoServiceChannel : Dataweb.Dilab.Web.ProdutoServiceReference.IProdutoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ProdutoServiceClient : System.ServiceModel.ClientBase<Dataweb.Dilab.Web.ProdutoServiceReference.IProdutoService>, Dataweb.Dilab.Web.ProdutoServiceReference.IProdutoService {
        
        public ProdutoServiceClient() {
        }
        
        public ProdutoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProdutoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProdutoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProdutoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Dataweb.Dilab.Model.DataTransfer.Transacao[] FindAllTransacaoByLogin(string login) {
            return base.Channel.FindAllTransacaoByLogin(login);
        }
        
        public Dataweb.Dilab.Model.DataTransfer.Transacao[] FindAllTransacaoByLoginAndReferencia(string login, string referencia) {
            return base.Channel.FindAllTransacaoByLoginAndReferencia(login, referencia);
        }
        
        public Dataweb.Dilab.Model.DataTransfer.Familia[] FindAllFamilia() {
            return base.Channel.FindAllFamilia();
        }
        
        public Dataweb.Dilab.Model.DataTransfer.Material[] FindAllMaterial() {
            return base.Channel.FindAllMaterial();
        }
        
        public int GetCountFechadas(int codCliente) {
            return base.Channel.GetCountFechadas(codCliente);
        }
        
        public int GetCountEmProducao(int codCliente) {
            return base.Channel.GetCountEmProducao(codCliente);
        }
        
        public Dataweb.Dilab.Model.DataTransfer.Item[] FindAllServico(int codFamilia) {
            return base.Channel.FindAllServico(codFamilia);
        }
        
        public Dataweb.Dilab.Model.DataTransfer.Item[] FindAllProduto(int codFamilia) {
            return base.Channel.FindAllProduto(codFamilia);
        }
        
        public Dataweb.Dilab.Model.DataTransfer.Transacao GetTransacao(int codEmpresa, int codTransacao) {
            return base.Channel.GetTransacao(codEmpresa, codTransacao);
        }
        
        public Dataweb.Dilab.Model.DataTransfer.OrdemServico GetOrdemServico(int codEmpresa, int codTransacao) {
            return base.Channel.GetOrdemServico(codEmpresa, codTransacao);
        }
        
        public Dataweb.Dilab.Model.DataTransfer.Pedido GetPedido(int codEmpresa, int codTransacao) {
            return base.Channel.GetPedido(codEmpresa, codTransacao);
        }
        
        public Dataweb.Dilab.Model.DataTransfer.OrdemServico InsertOrdemServico(Dataweb.Dilab.Model.DataTransfer.OrdemServico dto) {
            return base.Channel.InsertOrdemServico(dto);
        }
        
        public Dataweb.Dilab.Model.DataTransfer.Pedido InsertPedido(Dataweb.Dilab.Model.DataTransfer.Pedido dto) {
            return base.Channel.InsertPedido(dto);
        }
        
        public Dataweb.Dilab.Model.DataTransfer.Fatura[] FindAllFatura(int codEmpresa) {
            return base.Channel.FindAllFatura(codEmpresa);
        }
        
        public Dataweb.Dilab.Model.DataTransfer.Lancamento[] FindAllLancamento(int codEmpresa) {
            return base.Channel.FindAllLancamento(codEmpresa);
        }
        
        public Dataweb.Dilab.Model.DataTransfer.NotaFiscal[] FindAllNotaFiscal(int codEmpresa) {
            return base.Channel.FindAllNotaFiscal(codEmpresa);
        }
        
        public Dataweb.Dilab.Model.DataTransfer.Fatura GetFatura(int codEmpresa, int codFatura) {
            return base.Channel.GetFatura(codEmpresa, codFatura);
        }
        
        public Dataweb.Dilab.Model.DataTransfer.NotaFiscal GetNotaFiscal(int codEmpresa, int codNotaFiscal) {
            return base.Channel.GetNotaFiscal(codEmpresa, codNotaFiscal);
        }
    }
}
